document.getElementById('page-title').innerText = 'How to Train Your Dragon';
let paragraph = document.getElementById('paragraph');
paragraph.style.color = 'rgb(158, 123, 246)';
document.getElementById('subtitle').innerText = 'Dragons are AWESOME!'
let subtitle = document.getElementById('subtitle');
subtitle.style.color = 'rgb(0, 204, 163)';
let primeiroParagrafo = document.getElementsByClassName('dois-paragrafos')[0];
primeiroParagrafo.style.color = 'brown';
let segundoParagrafo = document.getElementsByTagName('p')[1];
segundoParagrafo.style.textAlign = 'center';
segundoParagrafo.style.color = 'darkblue';
